name: Release

on:
  push:
    branches: [ master ]

permissions:
  checks: read
  statuses: write
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - run: npm install -g npm@latest
      - name: Install deps
        run: yarn

      - name: Run release.mjs
        run: node ./cli.mjs
        env:
          VERBOSE: ${{ secrets.VERBOSE }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PROVENANCE: true
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          PUSH_MAJOR_TAG: true
